# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
platform:
  envoyGateway:
    ingress:
      enabled: false
      httpToHTTPSRedirect:
        enabled: true
      domains: []
      certificates:
        provider: ""
        objectType: ""
        projectID: ""
        keyPrefix: ""
        address: ""
        mountPath: ""
        authMountPath: ""
        caCertPath: ""
    sdsSidecar:
      image:
        repository: ghcr.io/podplane/operator
        tag: "v0.7.2"
        pullPolicy: IfNotPresent

gateway-helm:
  crds:
    enabled: false
  global:
    images:
      envoyProxy:
        # Follow the Envoy version selected by Envoy Gateway. Keep the web
        # template sidecar aligned where possible to minimize cached images,
        # but prefer this version for maximum Envoy Gateway interoperability.
        image: docker.io/envoyproxy/envoy:distroless-v1.39.0
  config:
    envoyGateway:
      extensionApis:
        enableSDSSecretRef: true
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
