# Podplane <https://podplane.dev>
# Copyright 2026 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/values.yaml
flux2:
  # CRDs are managed by the fluxcd-crds chart.
  installCRDs: false

  # Podplane is Helm-only and does not run additional Flux controllers.
  helmController:
    create: true
  kustomizeController:
    create: false
  notificationController:
    create: false
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false

  policies:
    create: false
