# Podplane <https://podplane.dev>
# Copyright 2026 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: platform-components
description: Podplane component installation chart
type: application
version: "1.0.0"
appVersion: "1.0.0"
