# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
podplane:
  operator:
    namePrefix: platform-podplane-operator
    image:
      repository: ghcr.io/podplane/operator
      tag: "v0.7.0"
      pullPolicy: IfNotPresent
    serviceAccountName: platform-podplane-operator
    registry:
      auth:
        securePort: 9443
        backendTLSPolicy:
          enabled: true
          caCertificateRef:
            name: certificates.podplane.dev:workload:roots
    aggregatedApiService:
      securePort: 8443
    config:
      cluster:
        id: ""
        spiffe:
          trustDomain: ""
        oidc:
          issuerURL: ""
          clientID: ""
          usernameClaim: email
          groupsClaim: groups
      secrets:
        keyRotation: 6h
        allowSyncToKubernetesSecrets: false
        defaultProvider: ""
        providers: {}
      registry:
        auth:
          enabled: false
      ingressCertificates:
        provider: ""
        keyPrefix: ""
        checkInterval: 1h
        renewBefore: 720h
        acme: null
        domains: {}
      workloadCertificates:
        caPath: /var/run/podplane/certificates/workload-ca-key.pem
    # Additional environment variables for the operator container. Useful for
    # cloud/provider SDK configuration sourced from Kubernetes Secrets,
    # but using volumes for mounting secrets instead is the recommended approach.
    env: []
    envFrom: []
    # Additional volumes and mounts for the operator pod. For example, for
    # OpenBao and Vault provider tokens, mount a Secret at
    # /var/run/podplane/providers/<provider-name>/token.
    extraVolumes: []
    extraVolumeMounts: []
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    apiService:
      enabled: true
      group: secrets-api.podplane.dev
      version: v1beta1
    admissionPolicies:
      secretProviderClassRestriction:
        enabled: true
        excludeNamespacesWithLabel:
          enabled: false
          key: secrets.podplane.dev/secretproviderclass-restriction-policy
          value: bypass
    rbac:
      defaultRoles:
        enabled: true
        namePrefix: platform-podplane-secrets
