# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "podplane-operator.namePrefix" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "podplane-operator.labels" . | indent 4 }}
spec:
  secretName: {{ .Values.podplane.operator.tls.secretName }}
  dnsNames:
    - {{ include "podplane-operator.namePrefix" . }}
    - {{ include "podplane-operator.namePrefix" . }}.{{ .Release.Namespace }}
    - {{ include "podplane-operator.namePrefix" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: {{ .Values.podplane.operator.tls.issuerRef.kind }}
    name: {{ .Values.podplane.operator.tls.issuerRef.name }}
