# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podplane-operator.namePrefix" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "podplane-operator.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "podplane-operator.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "podplane-operator.selectorLabels" . | indent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: operator
    spec:
      serviceAccountName: {{ include "podplane-operator.serviceAccountName" . }}
      containers:
        - name: operator
          image: {{ printf "%s:%s" .Values.podplane.operator.image.repository .Values.podplane.operator.image.tag | quote }}
          imagePullPolicy: {{ .Values.podplane.operator.image.pullPolicy }}
          args:
            - --config=/config/config.json
            - --serving-namespace={{ .Release.Namespace }}
            - --aggregated-api-bind-address=:{{ .Values.podplane.operator.aggregatedApiService.securePort }}
            - --aggregated-api-tls-cert-file=/var/run/podplane/serving/aggregated-api/tls.crt
            - --aggregated-api-tls-private-key-file=/var/run/podplane/serving/aggregated-api/tls.key
            - --aggregated-api-service-name={{ include "podplane-operator.namePrefix" . }}-aggregated-api
{{- if eq (include "podplane-operator.registryAuth.enabled" .) "true" }}
            - --registry-auth-bind-address=:{{ .Values.podplane.operator.registry.auth.securePort }}
            - --registry-auth-tls-cert-file=/var/run/podplane/serving/registry-auth/tls.crt
            - --registry-auth-tls-private-key-file=/var/run/podplane/serving/registry-auth/tls.key
            - --registry-auth-service-name={{ include "podplane-operator.namePrefix" . }}-registry-auth
{{- end }}
          ports:
            - name: aggregated-api
              containerPort: {{ .Values.podplane.operator.aggregatedApiService.securePort }}
{{- if eq (include "podplane-operator.registryAuth.enabled" .) "true" }}
            - name: registry-auth
              containerPort: {{ .Values.podplane.operator.registry.auth.securePort }}
{{- end }}
{{- with .Values.podplane.operator.env }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.podplane.operator.envFrom }}
          envFrom:
{{ toYaml . | indent 12 }}
{{- end }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /readyz
              port: aggregated-api
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /livez
              port: aggregated-api
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: workload-ca-key
              mountPath: /var/run/podplane/certificates
              readOnly: true
            - name: aggregated-api-serving-tls
              mountPath: /var/run/podplane/serving/aggregated-api
{{- if eq (include "podplane-operator.registryAuth.enabled" .) "true" }}
            - name: registry-auth-serving-tls
              mountPath: /var/run/podplane/serving/registry-auth
{{- end }}
            - name: config
              mountPath: /config
              readOnly: true
{{- with .Values.podplane.operator.extraVolumeMounts }}
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.podplane.operator.resources | indent 12 }}
      volumes:
        - name: workload-ca-key
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: platform-podplane-operator
        - name: aggregated-api-serving-tls
          emptyDir: {}
{{- if eq (include "podplane-operator.registryAuth.enabled" .) "true" }}
        - name: registry-auth-serving-tls
          emptyDir: {}
{{- end }}
        - name: config
          configMap:
            name: {{ include "podplane-operator.namePrefix" . }}-config
{{- with .Values.podplane.operator.extraVolumes }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podplane.operator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podplane.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podplane.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
