# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: agent-sandbox-crds
description: Agent Sandbox CRDs chart
type: application
version: "1.0.0"
appVersion: "v0.5.0"
