# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.platform.traefik.ingress.enabled }}
{{- $defaultDomain := include "podplane.traefik.defaultDomain" . | fromJson -}}
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: {{ include "podplane.traefik.secretName" $defaultDomain }}
{{- end }}
