# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-group-editors-crb
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: podplane:editors
# Cluster editors can modify workloads, but do not receive shell access to running pods.
# Note: Restrictions on container exec/shell access is done via editor-shell-vap
# For the same permissions but with exec/shell access, use the operators role.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
