# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: gateway-api-crds
description: Podplane Gateway API CRDs chart
type: application
version: "1.0.0"
appVersion: "1.3.0"
