# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
---
platform:
  certs:
    clusterCA:
      commonName: "podplane.local"
    service:
      selfsigned:
        issuerName: platform-service-certificate-clusterissuer
    ingress:
      acme:
        enabled: false
        issuerName: platform-ingress-acme-clusterissuer
        server: ""
        email: ""
        privateKeySecretName: platform-acme-account-key
        solvers: []
      selfsigned:
        issuerName: platform-ingress-selfsigned-clusterissuer
      dnsNames: []
    secretSync:
      enabled: false
      image:
        repository: registry.k8s.io/pause
        tag: 3.10.2
      mounts: []
