{{/*
Podplane <https://podplane.dev>
Copyright The Podplane Authors
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $apps := .Values.platform.components.apps -}}
---
# Cluster-wide namespace used as the target for cluster-scoped Helm releases (e.g. CRDs).
apiVersion: v1
kind: Namespace
metadata:
  name: platform-cluster
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: Helm
{{ range $name, $app := $apps }}
{{- $manage := true -}}
{{- if hasKey $app "manageNamespace" -}}{{- $manage = $app.manageNamespace -}}{{- end -}}
{{- if and $app.enabled $manage $app.namespace (ne $app.namespace "platform-cluster") }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $app.namespace }}
  annotations:
    helm.sh/resource-policy: keep
{{- with $app.namespaceAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/managed-by: Helm
{{- end }}
{{- end }}
