# Nstance <https://nstance.dev>
# Copyright The Nstance Authors
# SPDX-License-Identifier: Apache-2.0

{{- if and (not .Values.capi.endpoint) .Values.capi.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nstance-operator.capiServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nstance-operator.labels" . | nindent 4 }}
{{- end }}
