# Nstance <https://nstance.dev>
# Copyright The Nstance Authors
# SPDX-License-Identifier: Apache-2.0

{{- if and (not .Values.capi.endpoint) .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nstance-operator.fullname" . }}-capi-workload
  labels:
    {{- include "nstance-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
  - delete
# CAPI's runningOnWorkloadCluster check GETs its own pod via the kubeconfig
# to detect if management==workload cluster (which it is in our case)
# https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/clustercache/cluster_accessor_client.go#L145
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumes
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - list
- nonResourceURLs:
  - "/"
  verbs:
  - get
{{- end }}
