# Nstance <https://nstance.dev>
# Copyright The Nstance Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nstance-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nstance-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nstance-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nstance-operator.selectorLabels" . | nindent 8 }}
      {{- if or .Values.operatorConfigMap.enabled .Values.registrationSecret.enabled }}
      annotations:
        {{- if .Values.operatorConfigMap.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.registrationSecret.enabled }}
        checksum/registration-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nstance-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        command:
        - /nstance-operator
        args:
        - --leader-elect={{ .Values.leaderElection.enabled }}
        - --metrics-bind-address={{ ternary (printf ":%v" .Values.metrics.port) "0" .Values.metrics.enabled }}
        - --health-probe-bind-address=:{{ .Values.healthProbe.port }}
        - --zap-log-level={{ .Values.logLevel }}
        - --config=/etc/nstance/operator/config.yaml
        {{- if not .Values.webhooks.enabled }}
        - --disable-webhooks
        {{- end }}
        env:
        - name: NSTANCE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: NSTANCE_CA_CONFIGMAP
          value: {{ .Values.clusterCA.name }}
        - name: NSTANCE_NONCE_SECRET
          value: {{ .Values.registrationSecret.name }}
        - name: NSTANCE_KEY_SECRET
          value: {{ .Values.managedSecretNames.privateKey }}
        - name: NSTANCE_CERT_SECRET
          value: {{ .Values.managedSecretNames.clientCert }}
        - name: NSTANCE_CAPI_SERVICEACCOUNT
          value: {{ include "nstance-operator.capiServiceAccountName" . }}
        {{- with .Values.capi.endpoint }}
        - name: NSTANCE_CAPI_ENDPOINT
          value: {{ . | quote }}
        {{- end }}
        {{- if .Values.kubernetesJSON }}
        - name: NSTANCE_K8S_JSON
          value: "true"
        {{- end }}
        ports:
        {{- if .Values.metrics.enabled }}
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
        - name: health
          containerPort: {{ .Values.healthProbe.port }}
          protocol: TCP
        {{- if .Values.webhooks.enabled }}
        - name: webhook
          containerPort: 9443
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /etc/nstance/operator
          readOnly: true
        {{- if .Values.webhooks.enabled }}
        - name: webhook-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: {{ include "nstance-operator.configMapName" . }}
      {{- if .Values.webhooks.enabled }}
      - name: webhook-cert
        secret:
          secretName: {{ include "nstance-operator.webhookSecretName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
