# Nstance <https://nstance.dev>
# Copyright The Nstance Authors
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.deployment.enabled .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nstance-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nstance-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "nstance-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
{{- end }}
